input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        name:
         type:
           type_id: string
steps:
  example:
    plugin: quay.io/arcalot/arcaflow-plugin-example@sha256:4b9736645df26317586fdab6a3af250ecf6dc732df8d5ee24cad35436e5516c9
    input:
      name:
        _type: "nickname"
        nick: !expr $.input.name
output:
  message: !expr $.steps.example.outputs.success.message
