input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        name:
         type:
           type_id: string
steps:
  example:
    plugin: quay.io/arcalot/arcaflow-plugin-example:5a80de495338
    input:
      name:
        _type: "nickname"
        nick: !expr $.input.name
output:
  message: !expr $.steps.example.outputs.success.message
