version: v0.1.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}

steps:
  stressng_030:
#    plugin: quay.io/arcalot/arcaflow-plugin-stressng:0.3.0
#    plugin: localhost/stressng-test:latest
    #plugin: quay.io/arcalot/arcaflow-plugin-stressng:refactor_244ba7b
    plugin: quay.io/arcalot/arcaflow-plugin-stressng:refactor_3684fd3 # broken
    input:
      cleanup: false
      StressNGParams:
        timeout: 10s
        workdir: /tmp
        stressors:
          - stressor: cpu
            cpu_count: 1
            cpu_method: "all"
          - stressor: vm
            vm: 1
            vm_bytes: "1m"
          - stressor: matrix
            matrix: 1
          - stressor: mq
            mq: 1
          - stressor: hdd
            hdd: 1
            hdd_bytes: 1m
            hdd_write_size: 1m

outputs:
  success:
    stressng_0.2.0: !expr $.steps.stressng_030.outputs.success
