log:
  level: debug
deployer:
#  type: docker
  type: podman
#  deployment:
#    host:
#      NetworkMode: "host"
#    imagePullPolicy: Always
logged_outputs:
  error:
    level: error
  #success:
  #  level: info
