log:
  level: debug
deployer:
#  type: podman
  type: docker
  deployment:
    host:
      NetworkMode: "host"
    imagePullPolicy: Always
logged_outputs:
  error:
    level: error
  #success:
  #  level: info
