input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}
steps:
  long_wait:
    plugin: quay.io/joconnel/arcaflow-plugin-wait
    step: wait
    input:
      seconds: 60
  medium_wait:
    plugin: quay.io/joconnel/arcaflow-plugin-wait
    step: wait
    input:
      seconds: 50
    stop_if: !expr $.steps.short_wait.outputs
  short_wait:
    plugin: quay.io/joconnel/arcaflow-plugin-wait
    step: wait
    input:
      seconds: 1
outputs:
  a:
    b: !expr $.steps.medium_wait.outputs
