version: v0.1.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}
steps:
  long_wait:
    plugin: quay.io/arcalot/arcaflow-plugin-wait:atp-v3_6b769c6
    step: wait
    input:
      seconds: 20
  medium_wait:
    plugin: quay.io/arcalot/arcaflow-plugin-wait:atp-v3_6b769c6
    step: wait
    input:
      seconds: 4
    stop_if: !expr $.steps.short_wait.outputs
  short_wait:
    plugin: quay.io/arcalot/arcaflow-plugin-wait:atp-v3_6b769c6
    step: wait
    input:
      seconds: 1
outputs:
  a:
    b: !expr $.steps.medium_wait.outputs
