version: v0.1.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}
steps:
  python_wait:
    plugin: arcaflow-plugin-wait@git+https://github.com/arcalot/arcaflow-plugin-wait.git@93330402dcff63dcee3e3f5ba37b6a5266f6670d
    step: wait
    input:
      seconds: 4
  container_wait:
    plugin: quay.io/arcalot/arcaflow-plugin-wait:latest
    step: wait
    input:
      seconds: 4
    deploy:
      type: podman
outputs:
  a:
    python: !expr $.steps.python_wait.outputs
    container: !expr $.steps.container_wait.outputs

