version: v0.2.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}
steps:
  long_wait:
    plugin:
      src: arcaflow-plugin-wait@git+https://github.com/arcalot/arcaflow-plugin-wait.git@afdc2323805ffe2b37271f3a852a4ce7ac7379e1
      deployment_type: python
    step: wait
    input:
      seconds: 4
outputs:
  a:
    b: !expr $.steps.long_wait.outputs
