input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties: {}
steps:
  long_wait:
    plugin: arcaflow-plugin-wait@git+https://github.com/arcalot/arcaflow-plugin-wait.git@93330402dcff63dcee3e3f5ba37b6a5266f6670d
    step: wait
    input:
      seconds: 4
outputs:
  a:
    b: !expr $.steps.long_wait.outputs
