log:
  level: debug
deployer:
#  type: docker
  type: podman
#  connection:
#    host: "unix:///Users/joconnel/.lima/docker/sock/docker.sock"
  deployment:
#    host:
#      NetworkMode: "host"
    imagePullPolicy: IfNotPresent
logged_outputs:
  error:
    level: error
  #success:
  #  level: info
